version: '3.8'
services:
  firebase:
    image: andreysenov/firebase-tools
    volumes:
      - ./firebase:/home/node/app
      - ./firebase/data:/home/node/data
    ports:
      - "4000:4000"  # Emulator Suite UI
      - "9099:9099"  # Auth
      - "8080:8080"  # Cloud Firestore
    working_dir: /home/node/app
    command: firebase emulators:start --import=/home/node/data --export-on-exit=/home/node/data
